export const SUMMARY_LABELS = {
  title: 'summary.title',
  completed: 'summary.completed',
  updated: 'summary.updated',
  created: 'summary.created',
  dueSoon: 'summary.dueSoon',
  inLast7Days: 'summary.inLast7Days',
  inNext7Days: 'summary.inNext7Days',
  statusOverview: 'summary.statusOverview',
  viewAllWorkItems: 'summary.viewAllWorkItems',
  recentActivity: 'summary.recentActivity',
  stayUpToDate: 'summary.stayUpToDate',
  today: 'summary.today',
  yesterday: 'summary.yesterday',
  updatedField: 'summary.updatedField',
  filter: 'common.filter',
  totalWorkItems: 'summary.totalWorkItems',
  teamWorkload: 'summary.teamWorkload',
  monitorCapacity: 'summary.monitorCapacity',
  reassignWork: 'summary.reassignWork',
  workDistribution: 'summary.workDistribution',
  assignee: 'task.assignee',
  epicProgress: 'summary.epicProgress',
  useEpics: 'summary.useEpics',
  priorityBreakdown: 'summary.priorityBreakdown',
  typeBreakdown: 'summary.typeBreakdown',
};
